# Generated by Django 4.1.3 on 2022-11-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to=None, verbose_name='Foto del jugador'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(upload_to=None, verbose_name='Bandera del equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_crest',
            field=models.ImageField(upload_to=None, verbose_name='Escudo del equipo'),
        ),
    ]
